name: Security Vulnerability
description: Report a security vulnerability
title: "[Security]: "
labels: ["security", "needs-triage"]
assignees: []

body:
  - type: markdown
    attributes:
      value: |
        **IMPORTANT**: Please do not report security vulnerabilities through public GitHub issues. Instead, please follow our responsible disclosure process outlined below.

  - type: dropdown
    id: severity
    attributes:
      label: Severity Level
      description: How severe is this security issue?
      options:
        - Critical (Remote code execution, data breach)
        - High (Privilege escalation, authentication bypass)
        - Medium (Information disclosure, denial of service)
        - Low (Minor security issue)
    validations:
      required: true

  - type: dropdown
    id: component
    attributes:
      label: Affected Component
      description: Which component is affected by this vulnerability?
      options:
        - Wallet Core
        - Transaction Handling
        - Private Key Management
        - Network Communication
        - IPC Communication
        - File System Access
        - UI/Renderer Process
        - Dependencies
        - Other
    validations:
      required: true

  - type: textarea
    id: description
    attributes:
      label: Vulnerability Description
      description: A clear and concise description of the security vulnerability
      placeholder: Describe the security vulnerability...
    validations:
      required: true

  - type: textarea
    id: impact
    attributes:
      label: Potential Impact
      description: What is the potential impact of this vulnerability?
      placeholder: Describe the potential impact on users and the system...
    validations:
      required: true

  - type: textarea
    id: reproduction
    attributes:
      label: Steps to Reproduce
      description: Steps to reproduce the vulnerability (if applicable)
      placeholder: |
        1. Step 1
        2. Step 2
        3. Step 3
      render: shell

  - type: textarea
    id: environment
    attributes:
      label: Environment
      description: Environment details where the vulnerability was discovered
      placeholder: |
        - OS:
        - Neptune Core Wallet Version:
        - Node.js Version:
        - Other relevant details:
    validations:
      required: true

  - type: textarea
    id: disclosure
    attributes:
      label: Responsible Disclosure
      description: Please confirm you understand our responsible disclosure process
      placeholder: |
        I understand that:
        1. I will not publicly disclose this vulnerability until it has been patched
        2. I will work with the maintainers to coordinate the disclosure timeline
        3. I will provide reasonable time for the issue to be fixed before public disclosure
    validations:
      required: true

  - type: checkboxes
    id: terms
    attributes:
      label: Responsible Disclosure Agreement
      description: By submitting this security report, you agree to our responsible disclosure terms
      options:
        - label: I agree to follow responsible disclosure practices and will not publicly disclose this vulnerability until it has been patched
          required: true
        - label: I understand that this report will be handled confidentially
          required: true
